### ISSUE TITLE
MPI3D dataset Link is down

### ISSUE THREAD

**Issue by qinenergy** [causality-and-transfer-learning/disentanglement_dataset#3]
Hi,
I Really like the dataset! 

Is it maybe possible to update the link for the **mpi3d_toy**, **mpi3d_real**, and **mpi3d_realistic**?  The old ones (google cloud links) can not be accessed anymore.  A copy of it is available [online](https://transfer.thuml.ai/_modules/tllib/vision/datasets/regression/mpi3d.html) but it does not contain all ground truth labels. Thank you very much!

```
UserProjectAccountProblemThe project to be billed is associated with a closed billing account.The billing account for the owning project is disabled in state closed
```

Best regards,
Qin

**Comment by u-kob** [comment]
Hi Qin

I found the same problem, but I guess the order of the images is simple as described in the README.

> The datasets are provided in the form of numpy arrays. Once the data is loaded, you can use array.reshape([6,6,2,3,3,40,40,64,64,3]) to obtain an array where the first 7 dimensions corresponds to data generative factors as in the table above

So, we can probably retrieve the original label just by reshape. The [code here](https://github.com/wildphoton/Compositional-Generalization/blob/main/src/datasets/mpi3d.py) does it. I'm not sure the mirrored dataset you posted keeps the original order though.
