### ISSUE TITLE
Download link not accessible

### ISSUE THREAD

**Issue by wuancong** [causality-and-transfer-learning/disentanglement_dataset#4]
Hi, 

The download links provided for mpi3d_toy, mpi3d_realistic and mpi3d_real are not accessible now. Could you provide new links for download? Thank you!

Sincerely,
Ancong Wu

**Comment by Cmeo97** [comment]
Same problem. Could you update the links please?

Bests,
Cristian

**Comment by dion-jy** [comment]
I made a backup service for `mpi3d-real` dataset. (Unfortunately, I couldn't get the other three datasets)
You guys can use this dataset if you are struggling due to unavailable links.
https://github.com/CUN-bjy/mpi3d_real

**Comment by dion-jy** [comment]
@wuancong thank you for sharing of pre-downloaded dataset!!

**Comment by liyufeng183** [comment]
Same problem.Is there anyone has some available unofficial download link? 
thanks

**Comment by fan-yang1** [comment]
> Same problem.Is there anyone has some available unofficial download link? thanks

dataset available from unofficial link: https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/regression/mpi3d.py

**Comment by liyufeng183** [comment]
> > Same problem.Is there anyone has some available unofficial download link? thanks
> 
> dataset available from unofficial link: https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/regression/mpi3d.py

!!!Thank you for sharing the download link

**Comment by waleedgondal** [comment]
Super sorry for the delayed response. The download links have been updated

1. mpi3d_toy (simplistic rendered):  [link](https://storage.googleapis.com/mpi3d_disentanglement_dataset/data/mpi3d_toy.npz)
2. mpi3d_realistic (realistic rendered): [link](https://storage.googleapis.com/mpi3d_disentanglement_dataset/data/mpi3d_realistic.npz)
3. mpi3d_real (real-world images): [link](https://storage.googleapis.com/mpi3d_disentanglement_dataset/data/real.npz)
